### PR TITLE
add rudimentary unit testing

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by jrjohnson** [comment]
Want to go ahead and add an actions file as well so tests will run?

.github/workflows/ci.yaml
```yaml
name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: npm ci
    - name: test
      run: npm test
```

**Comment by Trott** [comment]
> Want to go ahead and add an actions file as well so tests will run?
> 
> .github/workflows/ci.yaml
> 
> ```yaml
> name: Continuous Integration
> 
> on:
>   push:
>     branches:
>       - master
>   pull_request:
> 
> env:
>   CI: true
> 
> jobs:
>   test:
>     name: Tests
>     runs-on: ubuntu-latest
> 
>     steps:
>     - uses: actions/checkout@v1
>     - uses: actions/setup-node@v1
>       with:
>         node-version: 12.x
>     - name: install dependencies
>       run: npm ci
>     - name: test
>       run: npm test
> ```

Since there's no `package-lock.json` file, I imagine `npm ci` needs to be `npm install` instead. (Or we need to check in a `package-lock.json` file. Actually, I think I prefer that, but whichever.)

Want to open up a separate PR to add this action file? The `npm test` task already exists (it just lints) so there's no reason to couple the GitHub action to this PR.

**Comment by jrjohnson** [comment]
Yup done. My local wasn't up to date so I was still seeing an empty `npm test` command. Once that is merged and this is rebased I think this is good to go, I'm just too lazy to check it out and run the tests so I want to see github do it for me.

**Review by stopfstedt — APPROVED** [review]
LGTM

**Comment by Trott** [comment]
Rebased and force-pushed to see if it kicks off the GitHub Action test.

**Comment by Trott** [comment]
> Rebased and force-pushed to see if it kicks off the GitHub Action test.

Success! (Well, success if the test actually passes, but the Action kicked off.)

**Comment by Trott** [comment]
There we go. Now it's green.

**Pull request merged**
